@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.pbf.comparator"
    
    Application <|-- PbfComparatorApplication
    class PbfComparatorApplication
    {
        --(constructors)--
        #PbfComparatorApplication()
        --
        +void compare(File before, File after)
        +void main(String[] arguments)
    }
    
@enduml

