@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.query.program.expressions.logical"
    
    interface BooleanExpression
    
    Node <|-- And
    BooleanExpression <|-- And
    class And
    {
        --(constructors)--
        +And(BooleanExpression, BooleanExpression)
    }
    
    Node <|-- Not
    BooleanExpression <|-- Not
    class Not
    {
        --(constructors)--
        +Not(BooleanExpression)
    }
    
    Node <|-- Or
    BooleanExpression <|-- Or
    class Or
    {
        --(constructors)--
        +Or(BooleanExpression, BooleanExpression)
    }
    
@enduml

