
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.graph.ways.extractor"
    
    Application <|-- DoubleDigitizedWaysExtractorApplication
    class DoubleDigitizedWaysExtractorApplication
    {
        --
        +void main(String[] arguments)
    }
    
@enduml

