
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.ui.desktop.viewer"
    
    class DrawableIdentifier
    {
        --(constructors)--
        +DrawableIdentifier(Object)
    }
    
    interface View
    View <|-- InteractiveView
    interface InteractiveView
    {
        --
        +void frameComplete()
        +void frameSpeed(Duration delay)
        +void zoomTo(Rectangle bounds)
        +void zoomToContents(Percent margin)
    }
    
    interface Named
    Named <|-- View
    interface View
    {
        --
        +void pullToFront(DrawableIdentifier)
        +void update(DrawableIdentifier, MapDrawable object)
        --(collection)--
        +void add(MapDrawable)
        +void clear()
        +void map(Function<MapDrawable,MapDrawable> consumer)
        +void pushToBack(DrawableIdentifier)
        +void remove(DrawableIdentifier)
    }
    
    interface Viewer
    {
        --
        +View view(String title)
        +Collection<View> views()
    }
    
@enduml

