
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.specifications.osm.graph"
    
    CommonGraph <|-- OsmGraph
    class OsmGraph
    {
        --(constructors)--
        +OsmGraph(Metadata)
        --
        +void markEdges()
        +void markJunctionEdges()
        +void markRampsAndConnectors()
        --(primitive)--
        +void markDoubleDigitizedEdges()
    }
    
@enduml

