@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.geocoding.reverse.matching"
    
    interface RoadNameMatcher
    
    RoadNameMatcher <|-- FuzzyRoadNameMatcher
    class FuzzyRoadNameMatcher
    {
    }
    
    interface RoadNameMatcher
    {
        --(math)--
        +Percent matches(RoadName candidate, RoadName desired)
    }
    
@enduml

