@startuml

    !include lexakai.theme
    
    title "mesakit-tools-applications-pbf-dumper"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact woodstox_core
    artifact gson
    artifact protobuf_java
    artifact cactus_build_metadata
    artifact kivakit_application
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_component
    artifact kivakit_conversion
    artifact kivakit_core
    artifact kivakit_data_compression
    artifact kivakit_data_formats_library
    artifact kivakit_extraction
    artifact kivakit_interfaces
    artifact kivakit_math
    artifact kivakit_mixins
    artifact kivakit_primitive_collections
    artifact kivakit_resource
    artifact kivakit_serialization_core
    artifact kivakit_serialization_gson
    artifact kivakit_serialization_kryo
    artifact kivakit_serialization_properties
    artifact kivakit_settings
    artifact kivakit_validation
    artifact lexakai_annotations
    artifact mesakit_map_data_formats_pbf
    artifact mesakit_map_data_library
    artifact mesakit_map_geography
    artifact mesakit_tools_applications_pbf_dumper
    artifact kryo_serializers
    artifact junit
    artifact jpf
    artifact commons_compress
    artifact commons_math
    artifact stax2_api
    artifact hamcrest_core
    artifact annotations
    artifact objenesis
    artifact osmosis_core
    artifact osmosis_osm_binary
    artifact osmosis_pbf
    artifact asm
    artifact spring_beans
    artifact spring_core
    artifact spring_jcl
    artifact spring_jdbc
    artifact spring_tx
    artifact xercesImpl
    junit --> hamcrest_core
    kivakit_application --> kivakit_commandline
    kivakit_application --> kivakit_component
    kivakit_commandline --> kivakit_collections
    kivakit_commandline --> kivakit_conversion
    kivakit_commandline --> kivakit_core
    kivakit_commandline --> kivakit_validation
    kivakit_component --> kivakit_settings
    kivakit_core --> cactus_build_metadata
    kivakit_core --> junit
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_data_compression --> kivakit_primitive_collections
    kivakit_data_formats_library --> kivakit_resource
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_math --> commons_math
    kivakit_primitive_collections --> kivakit_serialization_kryo
    kivakit_serialization_gson --> gson
    kivakit_serialization_kryo --> kivakit_serialization_core
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kivakit_settings --> kivakit_serialization_gson
    kivakit_settings --> kivakit_serialization_properties
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    mesakit_map_data_formats_pbf --> kivakit_data_compression
    mesakit_map_data_formats_pbf --> kivakit_data_formats_library
    mesakit_map_data_formats_pbf --> kivakit_extraction
    mesakit_map_data_formats_pbf --> kivakit_math
    mesakit_map_data_formats_pbf --> mesakit_map_data_library
    mesakit_map_data_formats_pbf --> osmosis_core
    mesakit_map_data_formats_pbf --> osmosis_osm_binary
    mesakit_map_data_formats_pbf --> osmosis_pbf
    mesakit_tools_applications_pbf_dumper --> kivakit_application
    mesakit_tools_applications_pbf_dumper --> mesakit_map_data_formats_pbf
    mesakit_tools_applications_pbf_dumper --> mesakit_map_geography
    osmosis_core --> commons_compress
    osmosis_core --> jpf
    osmosis_core --> spring_jdbc
    osmosis_core --> stax2_api
    osmosis_core --> woodstox_core
    osmosis_core --> xercesImpl
    osmosis_osm_binary --> protobuf_java
    reflectasm --> asm
    spring_core --> spring_jcl
    spring_jdbc --> spring_beans
    spring_jdbc --> spring_core
    spring_jdbc --> spring_tx
    
@enduml
