
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.overpass.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramOverpass
    class DiagramOverpass
    {
    }
    
@enduml

