@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.ui.desktop.theme"
    
    class MapColors
    {
    }
    
    class MapStrokes
    {
    }
    
    class MapStyles
    {
    }
    
@enduml

