
@startuml

    !include lexakai.theme
    
    title "mesakit-tools-applications-graph-analyzer"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact woodstox_core
    artifact flatlaf
    artifact gson
    artifact google_maps_services
    artifact protobuf_java
    artifact okhttp
    artifact okio
    artifact cactus_metadata
    artifact kivakit_application
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_component
    artifact kivakit_conversion
    artifact kivakit_core
    artifact kivakit_data_compression
    artifact kivakit_data_formats_library
    artifact kivakit_extraction
    artifact kivakit_interfaces
    artifact kivakit_math
    artifact kivakit_mixins
    artifact kivakit_network_core
    artifact kivakit_network_http
    artifact kivakit_primitive_collections
    artifact kivakit_resource
    artifact kivakit_serialization_core
    artifact kivakit_serialization_gson
    artifact kivakit_serialization_kryo
    artifact kivakit_serialization_properties
    artifact kivakit_settings
    artifact kivakit_ui_desktop
    artifact kivakit_validation
    artifact lexakai_annotations
    artifact mesakit_core
    artifact mesakit_graph_core
    artifact mesakit_map_data_formats_pbf
    artifact mesakit_map_data_library
    artifact mesakit_map_geography
    artifact mesakit_map_measurements
    artifact mesakit_map_overpass
    artifact mesakit_map_region
    artifact mesakit_map_road_model
    artifact mesakit_map_road_name_parser
    artifact mesakit_map_road_name_standardizer
    artifact mesakit_map_ui_debug
    artifact mesakit_map_ui_desktop
    artifact mesakit_map_utilities_grid
    artifact mesakit_tools_applications_graph_analyzer
    artifact commons_codec
    artifact commons_logging
    artifact kryo_serializers
    artifact grpc_context
    artifact opencensus_api
    artifact jpf
    artifact commons_compress
    artifact commons_lang3
    artifact commons_math
    artifact httpclient
    artifact httpcore
    artifact stax2_api
    artifact kotlin_stdlib_common
    artifact annotations
    artifact objenesis
    artifact osmosis_core
    artifact osmosis_osm_binary
    artifact osmosis_pbf
    artifact osmosis_xml
    artifact asm
    artifact slf4j_api
    artifact spring_beans
    artifact spring_core
    artifact spring_jcl
    artifact spring_jdbc
    artifact spring_tx
    artifact xercesImpl
    google_maps_services --> okhttp
    google_maps_services --> opencensus_api
    google_maps_services --> slf4j_api
    httpclient --> commons_logging
    httpclient --> httpcore
    kivakit_application --> kivakit_commandline
    kivakit_application --> kivakit_component
    kivakit_commandline --> kivakit_collections
    kivakit_commandline --> kivakit_conversion
    kivakit_commandline --> kivakit_core
    kivakit_commandline --> kivakit_validation
    kivakit_core --> cactus_metadata
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_math --> commons_math
    kivakit_network_http --> httpclient
    kivakit_network_http --> kivakit_network_core
    kivakit_primitive_collections --> kivakit_serialization_kryo
    kivakit_serialization_gson --> gson
    kivakit_serialization_kryo --> kivakit_serialization_core
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kivakit_settings --> kivakit_resource
    kivakit_settings --> kivakit_serialization_gson
    kivakit_settings --> kivakit_serialization_properties
    kivakit_ui_desktop --> flatlaf
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    mesakit_graph_core --> commons_lang3
    mesakit_graph_core --> kivakit_primitive_collections
    mesakit_graph_core --> kivakit_settings
    mesakit_graph_core --> mesakit_map_data_formats_pbf
    mesakit_graph_core --> mesakit_map_measurements
    mesakit_graph_core --> mesakit_map_overpass
    mesakit_graph_core --> mesakit_map_region
    mesakit_graph_core --> mesakit_map_road_name_standardizer
    mesakit_graph_core --> mesakit_map_ui_debug
    mesakit_graph_core --> mesakit_map_ui_desktop
    mesakit_graph_core --> mesakit_map_utilities_grid
    mesakit_map_data_formats_pbf --> kivakit_data_compression
    mesakit_map_data_formats_pbf --> kivakit_data_formats_library
    mesakit_map_data_formats_pbf --> kivakit_extraction
    mesakit_map_data_formats_pbf --> mesakit_map_data_library
    mesakit_map_data_formats_pbf --> osmosis_core
    mesakit_map_data_formats_pbf --> osmosis_osm_binary
    mesakit_map_data_formats_pbf --> osmosis_pbf
    mesakit_map_geography --> google_maps_services
    mesakit_map_measurements --> kivakit_math
    mesakit_map_overpass --> osmosis_xml
    mesakit_map_region --> kivakit_network_http
    mesakit_map_region --> mesakit_core
    mesakit_map_region --> mesakit_map_geography
    mesakit_map_road_name_parser --> mesakit_map_road_model
    mesakit_map_road_name_standardizer --> mesakit_map_road_name_parser
    mesakit_map_ui_desktop --> kivakit_ui_desktop
    mesakit_tools_applications_graph_analyzer --> kivakit_application
    mesakit_tools_applications_graph_analyzer --> mesakit_graph_core
    okhttp --> okio
    okio --> kotlin_stdlib_common
    opencensus_api --> grpc_context
    osmosis_core --> commons_compress
    osmosis_core --> jpf
    osmosis_core --> spring_jdbc
    osmosis_core --> stax2_api
    osmosis_core --> woodstox_core
    osmosis_core --> xercesImpl
    osmosis_osm_binary --> protobuf_java
    osmosis_xml --> commons_codec
    reflectasm --> asm
    spring_core --> spring_jcl
    spring_jdbc --> spring_beans
    spring_jdbc --> spring_core
    spring_jdbc --> spring_tx
    
@enduml
