
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.core"
    
    Project <|-- MesaKit
    class MesaKit
    {
        --(filesystem)--
        +Folder mesakitAllVersionsCacheFolder()
        +Folder mesakitCacheFolder()
        +Folder mesakitRootCacheFolder()
    }
    
@enduml

