
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.query.program.expressions.relational"
    
    interface BooleanExpression
    
    Node <|-- Then
    BooleanExpression <|-- Then
    class Then
    {
        --(constructors)--
        +Then(BooleanExpression, BooleanExpression)
    }
    
@enduml

