@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.serialization.json"
    
    abstract BaseGsonFactorySource
    
    BaseGsonFactorySource <|-- MesaKitGsonFactorySource
    class MesaKitGsonFactorySource
    {
    }
    
@enduml

