@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.serialization.json.serializers"
    
    interface GsonSerializer
    
    PrimitiveGsonSerializer <|-- DistanceGsonSerializer
    class DistanceGsonSerializer
    {
        --(constructors)--
        +DistanceGsonSerializer()
    }
    
    PrimitiveGsonSerializer <|-- IdentifierGsonSerializer
    class IdentifierGsonSerializer
    {
        --(constructors)--
        +IdentifierGsonSerializer()
    }
    
    GsonSerializer <|-- LatitudeGsonSerializer
    class LatitudeGsonSerializer
    {
    }
    
    GsonSerializer <|-- LocationGsonSerializer
    class LocationGsonSerializer
    {
    }
    
    GsonSerializer <|-- LongitudeGsonSerializer
    class LongitudeGsonSerializer
    {
    }
    
    PrimitiveGsonSerializer <|-- RectangleGsonSerializer
    class RectangleGsonSerializer
    {
        --(constructors)--
        +RectangleGsonSerializer()
    }
    
    GsonSerializer <|-- RectangleInDegreesGsonSerializer
    class RectangleInDegreesGsonSerializer
    {
    }
    
    PrimitiveGsonSerializer <|-- SpeedCategoryGsonSerializer
    class SpeedCategoryGsonSerializer
    {
        --(constructors)--
        +SpeedCategoryGsonSerializer()
    }
    
@enduml

