
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.region.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramBorder
    class DiagramBorder
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramRegion
    class DiagramRegion
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramRegions
    class DiagramRegions
    {
    }
    
@enduml

