
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.region.information"
    
    Application <|-- RegionInformationApplication
    class RegionInformationApplication
    {
        --(constructors)--
        +RegionInformationApplication()
        --
        +void main(String[] arguments)
    }
    
@enduml

