
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.ui.viewer"
    
    DrawablePolyline <|-- DrawableEdge
    class DrawableEdge
    {
        --(constructors)--
        +DrawableEdge(Edge, Style)
        +DrawableEdge(Edge, Style, String)
    }
    
    MapDot <|-- DrawableLocation
    class DrawableLocation
    {
        --(constructors)--
        +DrawableLocation(Location, Style)
        +DrawableLocation(Location, Style, String)
    }
    
    MapPolyline <|-- DrawablePolyline
    class DrawablePolyline
    {
        --(constructors)--
        +DrawablePolyline(Polyline, Style, String)
    }
    
    DrawablePolyline <|-- DrawableRoute
    class DrawableRoute
    {
        --(constructors)--
        +DrawableRoute(Route, Style)
        +DrawableRoute(Route, Style, String)
    }
    
    DebugViewer <|-- GraphDebugViewer
    class GraphDebugViewer
    {
        --(constructors)--
        +GraphDebugViewer()
        --
        +void candidate(Route, String label)
        +void candidate(Edge, String label)
        +void candidate(Edge)
        +void candidate(Route)
        +void current(Route, String label)
        +void current(Edge)
        +void current(Route)
        +void current(Edge, String label)
        +void edge(Edge, String label)
        +void highlight(Edge, String label)
        +void highlight(Route, String label)
        +void route(Route, String label)
        --(collection)--
        +void clearCandidateEdge()
        +void clearCandidateRoute()
        +void clearCurrentEdge()
        +void clearCurrentRoute()
        +void clearHighlightEdge()
        +void clearHighlightRoute()
    }
    
@enduml

