@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.navigation.routing.promoters"
    
    interface LevelPromoter
    
    LevelPromoter <|-- FunctionalClassCounterLevelPromoter
    class FunctionalClassCounterLevelPromoter
    {
    }
    
@enduml

