
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.io.load.loaders.region"
    
    abstract BaseGraphLoader
    
    BaseGraphLoader <|-- RegionalGraphLoader
    abstract class RegionalGraphLoader
    {
        --(constructors)--
        #RegionalGraphLoader()
        --
        #EdgeSequence forwardEdges()
        #Graph sourceGraph()
        --(collection)--
        #Iterable<Place> places()
        #Iterable<EdgeRelation> relations()
    }
    
@enduml

