
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.ui.viewer.theme"
    
    KivaKitDarculaTheme <|-- GraphDebugViewerTheme
    class GraphDebugViewerTheme
    {
        --
        +Style styleCandidate()
        +Style styleCurrent()
        +Style styleEdge()
        +Style styleHighlight()
        +Style styleRoute()
    }
    
@enduml

