@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.library.osm.change"
    
    abstract BaseMutableWay
    
    interface TimestampContainer
    
    abstract class BaseMutableWay
    {
        --
        +void changeTag(String key, String baseValue, String enhancingValue)
        --(collection)--
        +String addNameTag(Edge base, Edge enhancing)
        +void addNewTags(PbfTagList tags)
        +String addOneWayTag(Edge base, Edge enhancing)
        +void addTag(String key, String value)
        +String addTag(Edge base, Edge enhancing, String tag)
    }
    
    class ConnectionPoint
    {
        --
        +Location location()
        +ConnectionPoint.Type type()
        --(functional)--
        +Polyline withFromEndConnected(Polyline shape)
        +Polyline withToEndConnected(Polyline shape)
    }
    
    enum ConnectionPoint.End
    {
        FROM
        TO
    }
    
    BaseMutableWay <|-- MutableWay
    class MutableWay
    {
        --(constructors)--
        +MutableWay(PbfNodeStore, Edge)
        +MutableWay(PbfNodeStore, PbfUserIdentifier, PbfUserName, PbfWayIdentifier, Polyline, PbfTagList, int)
        --
        +ConnectionPoint connect(Polyline shape, Distance maximumDistance, ConnectionPoint.End)
        +void shape(Polyline shape)
        +Polyline shape()
        --(conversion)--
        +PbfWay asPbfWay()
        --(identity)--
        +void changeSetIdentifier(PbfChangeSetIdentifier)
        +PbfWayIdentifier identifier()
        +Set<PbfNodeIdentifier> referencedNodes()
        +void userIdentifier(PbfUserIdentifier)
        --(naming)--
        +void name(RoadName)
        +void userName(PbfUserName)
        --(time)--
        +boolean isModified()
        +void modified(String modification)
    }
    
    BaseMutableWay <|-- NewWay
    class NewWay
    {
        --(constructors)--
        +NewWay(PbfNodeStore, Polyline, PbfTagList, boolean)
        --
        +String pbfTag(String key)
        +void referenceNodes()
        +void shape(Polyline shape)
        +Polyline shape()
        --(angle)--
        +Angle connectionAngle(NewWay that)
        --(checks)--
        +boolean isConnected(NewWay that)
        +boolean isSameWay(NewWay that)
        --(functional)--
        +NewWay connectedTo(NewWay extension)
        --(identity)--
        +PbfWayIdentifier identifier()
        +Set<MapNodeIdentifier> referencedNodes()
        --(naming)--
        +String name()
    }
    
    ArrayList <|-- PbfNodeIdentifierList
    class PbfNodeIdentifierList
    {
        --(constructors)--
        +PbfNodeIdentifierList(PbfNodeStore, Iterable<Location>)
        --
        +void append(Location)
        +void prepend(Location)
        --(collection)--
        +StringList references()
    }
    
    TimestampContainer <|-- PbfTimestamp
    class PbfTimestamp
    {
        --(constructors)--
        +PbfTimestamp()
        +PbfTimestamp(Date)
        +PbfTimestamp(long)
    }
    
    class RemovedWay
    {
        --(constructors)--
        +RemovedWay(PbfWayIdentifier)
    }
    
    enum ConnectionPoint.Type
    {
        OVERSHOOT
        TWO_SEGMENT_OVERSHOOT
        UNDERSHOOT
    }
    
@enduml

