@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.specifications.common.shapepoint"
    
    ShapePoint <|-- HeavyWeightShapePoint
    class HeavyWeightShapePoint
    {
        --(constructors)--
        +HeavyWeightShapePoint(Graph, long)
        --
        +void location(Location)
        +void pbfTags(PbfTagList pbfTags)
    }
    
    GraphElementAttributes.GraphElementAttribute <|-- ShapePointAttributes.ShapePointAttribute
    class ShapePointAttributes.ShapePointAttribute
    {
        --(constructors)--
        +ShapePointAttribute(String)
    }
    
    NodeAttributes <|-- ShapePointAttributes
    class ShapePointAttributes
    {
        --(constructors)--
        #ShapePointAttributes()
        --
        +ShapePointAttributes get()
    }
    
    GraphElementProperties <|-- ShapePointProperties
    class ShapePointProperties
    {
        --(constructors)--
        #ShapePointProperties()
        --
        +ShapePointProperties get()
    }
    
    GraphElementProperty <|-- ShapePointProperties.ShapePointProperty
    abstract class ShapePointProperties.ShapePointProperty
    {
        --(constructors)--
        #ShapePointProperty(String, Attribute<?>)
    }
    
@enduml

