@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.io.convert"
    
    interface Repeater
    Repeater <|-- GraphConverter
    interface GraphConverter
    {
        --
        +Graph convert(File input)
    }
    
@enduml

