@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.geocoding.reverse"
    
    class ReverseGeocoder.Configuration
    {
        --
        +Distance within()
        +void within(Distance within)
        --(angle)--
        +void compareDirection(boolean compare)
        +boolean compareDirection()
        +void headingTolerance(Angle headingTolerance)
        +Angle headingTolerance()
        --(naming)--
        +void roadNameCloseness(Percent roadNameCloseness)
        +Percent roadNameCloseness()
        +void roadNameMatcher(RoadNameMatcher)
        +RoadNameMatcher roadNameMatcher()
        +RoadNameStandardizer roadNameStandardizer()
        +void roadNameStandardizer(RoadNameStandardizer)
    }
    
    class ReverseGeocoder.Request
    {
        --
        +void location(Location)
        +Location location()
        --(angle)--
        +Heading heading()
        +void heading(Heading)
        --(naming)--
        +void roadName(RoadName)
        +RoadName roadName()
    }
    
    class ReverseGeocoder.Response
    {
        --
        +Edge edge()
        +PolylineSnap snap()
        --(math)--
        +Percent percentage()
    }
    
    class ReverseGeocoder
    {
        --(constructors)--
        +ReverseGeocoder(Graph, Configuration)
        --(search)--
        +Response locate(Request)
    }
    
@enduml

