@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.core"
    
    Project <|-- MesaKit
    class MesaKit
    {
        --
        +MesaKit get()
        --(filesystem)--
        +Folder mesakitAllVersionsCacheFolder()
        +Folder mesakitCacheFolder()
        +Folder mesakitExtensionsHome()
        +Folder mesakitHome()
        +Folder mesakitRootCacheFolder()
    }
    
@enduml

