@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.pbf.analyzer"
    
    abstract BaseComponent
    
    BaseComponent <|-- Analyzer
    class Analyzer
    {
        --(collection)--
        +void addWay(PbfWay)
    }
    
    Application <|-- PbfAnalyzerApplication
    class PbfAnalyzerApplication
    {
        --
        +void main(String[] arguments)
    }
    
@enduml

