@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.specifications.common.node.store.all.disk"
    
    class AllNodeDiskCell
    {
        --(constructors)--
        +AllNodeDiskCell(Located)
        +AllNodeDiskCell(Location)
        --(filesystem)--
        +String toFileString(String base)
    }
    
    abstract class AllNodeDiskStore
    {
        --(constructors)--
        #AllNodeDiskStore(Folder)
        #AllNodeDiskStore(GraphArchive)
        --
        +GraphArchive archive()
        #ZipEntry entry(AllNodeDiskCell)
        --(collection)--
        +boolean containsData()
        --(filesystem)--
        +Iterable<AllNodeDiskCell> DiskCells()
        +void delete()
        --(naming)--
        #String name()
        --(read)--
        +InputStream in(AllNodeDiskCell)
        #DataInputStream input(AllNodeDiskCell)
        --(write)--
        +void saveTo(GraphArchive)
        #DataOutputStream output(AllNodeDiskCell)
    }
    
    class PbfAllNodeDiskStores
    {
        --(constructors)--
        +PbfAllNodeDiskStores(Folder, FileName)
        --(collection)--
        +void add(PbfNode)
        +boolean containsData()
        --(filesystem)--
        +void delete()
        +PbfAllNodeIdentifierDiskStore pbfNodeIdentifierDiskStore()
        +PbfAllNodeIndexDiskStore pbfNodeIndexDiskStore()
        +PbfAllNodeMetadataDiskStore pbfNodeMetadataDiskStore()
        +PbfAllNodeTagDiskStore pbfNodeTagDiskStore()
        +Folder temporary()
        --(write)--
        +void saveTo(GraphArchive)
    }
    
    AllNodeDiskStore <|-- PbfAllNodeIdentifierDiskStore
    class PbfAllNodeIdentifierDiskStore
    {
        --(constructors)--
        +PbfAllNodeIdentifierDiskStore(Folder)
        +PbfAllNodeIdentifierDiskStore(GraphArchive)
        --(collection)--
        +void add(PbfNode)
        +LongArray load(AllNodeDiskCell)
    }
    
    AllNodeDiskStore <|-- PbfAllNodeIndexDiskStore
    class PbfAllNodeIndexDiskStore
    {
        --(constructors)--
        +PbfAllNodeIndexDiskStore(Folder)
        +PbfAllNodeIndexDiskStore(GraphArchive)
        --(collection)--
        +void add(PbfNode)
        +LongToIntMap load(AllNodeDiskCell)
    }
    
    AllNodeDiskStore <|-- PbfAllNodeMetadataDiskStore
    class PbfAllNodeMetadataDiskStore
    {
        --(constructors)--
        +PbfAllNodeMetadataDiskStore(Folder)
        +PbfAllNodeMetadataDiskStore(GraphArchive)
        --(collection)--
        +void add(PbfNode)
        --(metadata)--
        +PbfAllNodeMetadataStore load(GraphArchive, AllNodeDiskCell)
    }
    
    AllNodeDiskStore <|-- PbfAllNodeTagDiskStore
    class PbfAllNodeTagDiskStore
    {
        --(constructors)--
        +PbfAllNodeTagDiskStore(Folder)
        +PbfAllNodeTagDiskStore(GraphArchive, PbfTagCodec)
        --(collection)--
        +void add(PbfNode)
        --(read)--
        +PbfNodeTagStore load(Graph, AllNodeDiskCell)
    }
    
@enduml

