@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.io.save"
    
    class PbfGraphSaver
    {
        --(write)--
        +void save(Graph, WritableResource)
    }
    
@enduml

