@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.specifications.library.properties"
    
    interface Comparable
    interface Iterable
    
    Comparable <|-- GraphElementProperty
    abstract class GraphElementProperty<T>
    {
        --(constructors)--
        #GraphElementProperty(String, Attribute<?>, DataSpecification)
        --
        +Attribute<?> attribute()
        +boolean matches(DataSpecification)
        +String string(Object element)
        +Object valueFromObject(Object element)
        --(collection)--
        #Object value(T element)
        --(naming)--
        +String name()
    }
    
    Iterable <|-- GraphElementPropertySet
    class GraphElementPropertySet<T>
    {
        --(collection)--
        +GraphElementPropertySet<T> add(GraphElementPropertySet<T> that)
        +List<GraphElementProperty<T>> properties()
        #void add(GraphElementProperty<T>)
    }
    
@enduml

