@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.codec.polyline"
    
    abstract BaseComponent
    
    BaseComponent <|-- HuffmanCodecGenerator
    class HuffmanCodecGenerator
    {
        --(command line parsing)--
        +void run(CommandLine)
    }
    
@enduml

