
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.io.archive"
    
    abstract BaseStringConverter
    
    interface Named
    interface RegistryTrait
    
    BaseStringConverter <|-- GraphArchive.Converter
    RegistryTrait <|-- GraphArchive.Converter
    class GraphArchive.Converter
    {
        --(constructors)--
        +Converter(Listener)
        +Converter(Listener, ProgressReporter)
    }
    
    FieldArchive <|-- GraphArchive
    RegistryTrait <|-- GraphArchive
    Named <|-- GraphArchive
    class GraphArchive
    {
        --(constructors)--
        +GraphArchive(Listener, File, ZipArchive.AccessMode, ProgressReporter)
        --
        +Resource forSpecifier(Listener, String specifier)
        +Resource resource()
        --(command line parsing)--
        +ArgumentParser.Builder<Graph> argumentParser(Listener, String description)
        +SwitchParser.Builder<Graph> graphArchiveSwitchParser(Listener, String name, String description)
        +SwitchParser.Builder<GraphList> graphListSwitchParser(Listener, String name, String description)
        --(filtering)--
        +boolean accepts(FileName)
        --(metadata)--
        +Metadata metadata()
        +void saveMetadata(Metadata)
        --(read)--
        +Graph load(Listener)
        +Graph loadAll(Listener)
        --(time)--
        +Time lastModified()
    }
    
    BaseStringConverter <|-- GraphArchive.ListConverter
    class GraphArchive.ListConverter
    {
        --(constructors)--
        +ListConverter(Listener)
    }
    
@enduml

