@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.world.project"
    
    KryoTypes <|-- WorldGraphKryoTypes
    class WorldGraphKryoTypes
    {
        --(constructors)--
        +WorldGraphKryoTypes()
    }
    
    GraphUnitTest <|-- WorldGraphUnitTest
    class WorldGraphUnitTest
    {
        --
        +void testSetup()
    }
    
@enduml

