@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.plugins.josm.graph.view.tabs.search"
    
    abstract BaseComponent
    
    interface ComponentMixin
    
    JPanel <|-- SearchPanel
    ComponentMixin <|-- SearchPanel
    class SearchPanel
    {
        --(constructors)--
        +SearchPanel(GraphPanel)
        --
        +void html(String message, Object... arguments)
        +void text(String message, Object... arguments)
        --(write)--
        +OutputPanel console()
    }
    
    BaseComponent <|-- Searcher
    class Searcher
    {
        --(constructors)--
        +Searcher(GraphLayer)
        --(search)--
        +EdgeSet findTagged(Maximum, String searchString)
        +UserFeedback search(String searchString)
    }
    
    class TurnRestrictionStatistics
    {
        --
        +int badRestrictions()
        +int restrictions()
        --(collection)--
        +void add(EdgeRelation)
        +void add(EdgeRelation, boolean bad)
        +void addAll(Iterable<EdgeRelation> relations)
        +StringList summary()
    }
    
    class UserFeedback
    {
        --
        +String html()
        +UserFeedback html(String message, Object... arguments)
        +String text()
        +UserFeedback text(String message, Object... arguments)
        --(functional)--
        +UserFeedback withHtml(String message, Object... arguments)
        +UserFeedback withStatus(String message, Object... arguments)
        +UserFeedback withText(String message, Object... arguments)
        --(status)--
        +UserFeedback status(String message, Object... arguments)
        +String status()
    }
    
@enduml

