@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.pbf.graph.world.extractor.conversion"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- Conversion
    class Conversion
    {
        --(constructors)--
        +Conversion(PbfWorldGraphExtractorApplication, Folder, WorldCell)
        --
        +Graph convert(File input, Metadata)
    }
    
    class WorldConversion.Statistics
    {
        --(collection)--
        +Count attempted()
        +Count completed()
        +Count edgeRelations()
        +Count edges()
        +Count failed()
        +Count forwardEdges()
        +Count places()
        +Count succeeded()
        +Bytes totalSize()
        +Count vertexes()
        --(metadata)--
        +Metadata metadata(Metadata)
    }
    
    class WorldConversion
    {
        --(command line parsing)--
        +Statistics convert(PbfWorldGraphExtractorApplication, WorldGrid, CommandLine, Metadata, WorldGraphRepositoryFolder outputFolder, Count threads)
    }
    
@enduml

