@startuml

    !include lexakai.theme
    
    title "mesakit-map-ui-debug"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact flatlaf
    artifact gson
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_component
    artifact kivakit_configuration
    artifact kivakit_data_compression
    artifact kivakit_kernel
    artifact kivakit_math
    artifact kivakit_network_core
    artifact kivakit_network_http
    artifact kivakit_primitive_collections
    artifact kivakit_resource
    artifact kivakit_security
    artifact kivakit_serialization_core
    artifact kivakit_serialization_json
    artifact kivakit_serialization_kryo
    artifact kivakit_test
    artifact kivakit_ui_desktop
    artifact lexakai_annotations
    artifact mesakit_core
    artifact mesakit_map_geography
    artifact mesakit_map_measurements
    artifact mesakit_map_ui_debug
    artifact mesakit_map_ui_desktop
    artifact commons_codec
    artifact commons_logging
    artifact kryo_serializers
    artifact swagger_annotations
    artifact junit
    artifact commons_math
    artifact httpclient
    artifact httpcore
    artifact hamcrest_core
    artifact annotations
    artifact shapefilereader
    artifact objenesis
    artifact asm
    httpclient --> commons_codec
    httpclient --> commons_logging
    httpclient --> httpcore
    junit --> hamcrest_core
    kivakit_collections --> kivakit_serialization_kryo
    kivakit_component --> kivakit_configuration
    kivakit_configuration --> kivakit_serialization_json
    kivakit_data_compression --> kivakit_primitive_collections
    kivakit_kernel --> annotations
    kivakit_kernel --> cactus_build_metadata
    kivakit_kernel --> jackson_annotations
    kivakit_kernel --> lexakai_annotations
    kivakit_kernel --> swagger_annotations
    kivakit_math --> commons_math
    kivakit_network_core --> kivakit_commandline
    kivakit_network_core --> kivakit_security
    kivakit_network_http --> httpclient
    kivakit_network_http --> kivakit_network_core
    kivakit_resource --> kivakit_serialization_core
    kivakit_serialization_json --> gson
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kivakit_test --> junit
    kivakit_test --> kivakit_kernel
    kivakit_ui_desktop --> flatlaf
    kivakit_ui_desktop --> kivakit_resource
    kivakit_ui_desktop --> kivakit_test
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    mesakit_map_geography --> kivakit_collections
    mesakit_map_geography --> kivakit_component
    mesakit_map_geography --> kivakit_data_compression
    mesakit_map_geography --> kivakit_math
    mesakit_map_geography --> mesakit_map_measurements
    mesakit_map_geography --> shapefilereader
    mesakit_map_ui_debug --> mesakit_map_ui_desktop
    mesakit_map_ui_desktop --> kivakit_network_http
    mesakit_map_ui_desktop --> kivakit_ui_desktop
    mesakit_map_ui_desktop --> mesakit_core
    mesakit_map_ui_desktop --> mesakit_map_geography
    reflectasm --> asm
    
@enduml
