
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.plugins.josm.geojson"
    
    abstract BaseJosmLayer
    abstract BaseJosmPanel
    abstract BaseJosmPlugin
    
    interface NamedObject
    
    JPopupMenu <|-- GeoJsonFeaturePopUpMenu
    class GeoJsonFeaturePopUpMenu
    {
        --(constructors)--
        +GeoJsonFeaturePopUpMenu(GeoJsonFeature)
    }
    
    FileImporter <|-- GeoJsonFileImporter
    class GeoJsonFileImporter
    {
        --(constructors)--
        +GeoJsonFileImporter(GeoJsonPlugin)
    }
    
    BaseJosmLayer <|-- GeoJsonLayer
    NamedObject <|-- GeoJsonLayer
    class GeoJsonLayer
    {
        --(constructors)--
        +GeoJsonLayer(GeoJsonPlugin, String)
        --
        +GeoJsonDocument getDocument()
        +void setDocument(GeoJsonDocument)
        +void zoomToFeature(GeoJsonFeature)
        --(filesystem)--
        +File getFile()
        +void setFile(File)
    }
    
    BaseJosmPanel <|-- GeoJsonPanel
    class GeoJsonPanel
    {
        --(constructors)--
        +GeoJsonPanel(GeoJsonPlugin)
        --
        +void selectFeature(GeoJsonFeature)
        #void popup(MouseEvent)
        --(checks)--
        +boolean isVisible(GeoJsonFeature)
    }
    
    BaseJosmPlugin <|-- GeoJsonPlugin
    class GeoJsonPlugin
    {
        --(constructors)--
        +GeoJsonPlugin(PluginInformation)
        --(identity)--
        +int changeSetIdentifier()
    }
    
@enduml

