@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.library.osm.change.io"
    
    class JosmChangeFile
    {
        --
        +MutableWay modifiableWay(Edge)
        +MutableWay modifiableWay(Graph, PbfUserIdentifier, PbfUserName, PbfWayIdentifier, Polyline shape, PbfTagList tags, int version)
        --(collection)--
        +void add(NewWay)
        --(lifecycle)--
        +void connectFromEnd(ConnectionPoint, MutableWay)
        +void connectToEnd(ConnectionPoint, MutableWay)
        --(write)--
        +void save(File output)
        +void save(File output, boolean debug)
    }
    
    class JosmXml
    {
        --(constructors)--
        +JosmXml(WritableResource)
        --(collection)--
        +void addModifiedTags(boolean add)
        +void addModifiedWays(Collection<MutableWay> ways)
        +void addNewTags(boolean add)
        +void addNewWays(Collection<NewWay> ways)
        +void addNodes(PbfNodeStore)
        +void removeWay(PbfWayIdentifier)
        --(write)--
        +void save(boolean debug)
    }
    
    class PbfSaver
    {
        --(write)--
        +void save(Graph, File output)
    }
    
@enduml

