@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.graph.specifications.osm.graph.edge.model.attributes"
    
    GraphElementAttributes.GraphElementAttribute <|-- OsmEdgeAttributes.OsmEdgeAttribute
    class OsmEdgeAttributes.OsmEdgeAttribute
    {
        --(constructors)--
        +OsmEdgeAttribute(String)
    }
    
    EdgeAttributes <|-- OsmEdgeAttributes
    class OsmEdgeAttributes
    {
        --(constructors)--
        #OsmEdgeAttributes()
        --
        +OsmEdgeAttributes get()
    }
    
    class OsmEdgeDifferences
    {
        --(constructors)--
        +OsmEdgeDifferences(OsmEdge, OsmEdge)
        --
        +Differences compare()
    }
    
    EdgeProperties <|-- OsmEdgeProperties
    class OsmEdgeProperties
    {
        --(constructors)--
        #OsmEdgeProperties()
        --
        +OsmEdgeProperties get()
    }
    
    EdgeProperties.EdgeProperty <|-- OsmEdgeProperties.OsmEdgeProperty
    abstract class OsmEdgeProperties.OsmEdgeProperty
    {
        --(constructors)--
        #OsmEdgeProperty(String, Attribute<?>)
    }
    
@enduml

