@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.geography.project"
    
    KryoTypes <|-- GeographyKryoTypes
    class GeographyKryoTypes
    {
        --(constructors)--
        +GeographyKryoTypes()
    }
    
    class GeographyLimits
    {
    }
    
    MeasurementsRandomValueFactory <|-- GeographyRandomValueFactory
    class GeographyRandomValueFactory
    {
        --(constructors)--
        +GeographyRandomValueFactory()
        +GeographyRandomValueFactory(long)
        --(factory)--
        +Latitude newLatitude(Latitude min, Latitude max)
        +Latitude newLatitude()
        +Location newLocation()
        +Location newLocation(Rectangle bounds)
        +Longitude newLongitude()
        +Longitude newLongitude(Longitude min, Longitude max)
        +Rectangle newRectangle(Rectangle bounds)
        +Rectangle newRectangle()
        +Rectangle newRectangle(Rectangle bounds, Distance maximumRadius)
        +Size newSize(Size maximum)
        +Size newSize(Size min, Size max)
    }
    
    MeasurementsUnitTest <|-- GeographyUnitTest
    class GeographyUnitTest
    {
        --
        #Location location(double latitude, double longitude)
        #Rectangle rectangle(String rectangle)
    }
    
@enduml

