
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.tools.applications.codec.tag"
    
    abstract BaseComponent
    
    BaseComponent <|-- TagCodecGenerator
    class TagCodecGenerator
    {
        --(command line parsing)--
        +void run(CommandLine)
    }
    
@enduml

