@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.ui.desktop"
    
    Project <|-- MapDesktopUiProject
    class MapDesktopUiProject
    {
        --(constructors)--
        #MapDesktopUiProject()
        --(collection)--
        +MapDesktopUiProject get()
    }
    
@enduml

