
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.plugins.josm.graph.view.tabs.tags.indexing"
    
    abstract BaseRepeater
    
    class TagIndex
    {
        --(constructors)--
        +TagIndex(TagIndexRequest)
        --
        +EdgeSet edges(String key, String value)
        --(collection)--
        +Count keyCount()
        +StringList keys()
        +Count valueCount()
        +ObjectList<String> values(String key)
    }
    
    class TagIndexRequest
    {
        --(constructors)--
        +TagIndexRequest(Graph, Rectangle, Consumer<TagIndex>)
    }
    
    BaseRepeater <|-- TagIndexer
    class TagIndexer
    {
        --(constructors)--
        +TagIndexer()
        --(collection)--
        +void index(TagIndexRequest)
    }
    
@enduml

