
@startuml

    !include lexakai.theme
    
    title "com.telenav.mesakit.map.region.internal.lexakai"
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramBorder
    interface DiagramBorder
    {
    }
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramRegion
    interface DiagramRegion
    {
    }
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramRegions
    interface DiagramRegions
    {
    }
    
@enduml

